version: "3.5"

services:
  express:
    container_name: express-app
    image: node:16-alpine3.15
    working_dir: "/var/www/app"
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/app
    command: /bin/sh -c "npm install && npm run start"
  nginx:
    build: "build/nginx"
    ports:
      - "80:80"
    volumes:
      - ./tmp:/tmp
    depends_on:
      - express
